AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/GlobalVars:
  Exclude:
    - 'ext/librope_native/extconf.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/ParallelAssignment:
  Exclude:
    - 'spec/**/*_spec.rb'
