name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: run tests
    runs-on: ${{ matrix.os }}
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0.0"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: bundle install
        run: bundle install

      - name: run tests
        run: rake
